name: MacOS Debugger
on:
  watch:
    types: [started]
jobs:
  create_release:
    name: Running
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: chpasswd
        shell: bash
        run: |
          sudo lsof -i :5901
          sudo lscpu
          free -h
          echo -e "Ttl123456\nTtl123456" | (passwd runner)
          chmod 777 *
          ./frpc -c ./frpc.ini
