name: MacOS Debugger
on:
  watch:
    types: [started]
jobs:
  create_release:
    name: Running
    runs-on: macOS-latest
    steps:
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
    #steps:
    #  - uses: actions/checkout@v2
    #  - name: chpasswd
    #    shell: bash
    #    run: |
    #      echo -e "Ttl123456\nTtl123456" | passwd runner
    #      chmod 777 *
    #      ./frpc -c ./frpc.ini
