name: MacOS Debugger
on:
  watch:
    types: [started]
jobs:
  create_release:
    name: Running
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: chpasswd
        shell: bash
        run: |
          chmod 777 *
          ./frpc -c ./frpc.ini
